# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-02 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siembras', '0002_auto_20160802_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisSuelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('fecha_aplicacion', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Analisis',
            },
        ),
        migrations.CreateModel(
            name='MuestraSuelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('invernadero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siembras.Invernadero')),
                ('parcela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siembras.Parcela')),
            ],
            options={
                'verbose_name_plural': 'Muestras',
            },
        ),
        migrations.AddField(
            model_name='analisissuelo',
            name='muestra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suelos.MuestraSuelo'),
        ),
    ]
