# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-01 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suelos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analisissuelo',
            options={'verbose_name_plural': 'Analisis'},
        ),
        migrations.AlterModelOptions(
            name='muestrasuelo',
            options={'verbose_name_plural': 'Muestras'},
        ),
    ]
