# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-30 06:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Germinacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=0.0)),
                ('fecha_enviado', models.DateField()),
                ('fecha_recibido', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Lotes de Germinacion',
            },
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Proovedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=255)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('categoria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='siembras.Categoria')),
            ],
            options={
                'verbose_name_plural': 'Proovedores',
            },
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Semilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='nombre comercial semilla', max_length=255)),
                ('fecha_compra', models.DateField()),
                ('precio_compra', models.FloatField(default=0.0)),
                ('cantidad', models.FloatField(default=0.0)),
                ('unidad', models.IntegerField(choices=[(1, 'grs'), (2, 'unidad')], default=1)),
                ('codigo', models.CharField(blank=True, max_length=255)),
                ('nivel_germinacion', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)])),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siembras.Rubro')),
                ('proovedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siembras.Proovedor')),
            ],
        ),
        migrations.CreateModel(
            name='TipoParcela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='parcela',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siembras.TipoParcela'),
        ),
        migrations.AddField(
            model_name='germinacion',
            name='proovedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siembras.Proovedor'),
        ),
        migrations.AddField(
            model_name='germinacion',
            name='semilla_utilizada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siembras.Semilla'),
        ),
    ]
