# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-02 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siembras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('fecha_siembra', models.DateField(blank=True, null=True)),
                ('posicion_inicial', models.IntegerField()),
                ('posicion_final', models.IntegerField()),
                ('densidad_siembra', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Invernadero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(blank=True, max_length=255)),
                ('codigo', models.CharField(max_length=255, unique=True)),
                ('capacidad', models.IntegerField(default=500)),
            ],
        ),
        migrations.CreateModel(
            name='LoteSiembra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=0.0)),
                ('fecha_enviado', models.DateField(blank=True, null=True)),
                ('fecha_recibido', models.DateField(blank=True, null=True)),
                ('germinado', models.BooleanField(default=True)),
                ('proovedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siembras.Proovedor')),
                ('semilla_utilizada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siembras.Semilla')),
            ],
            options={
                'verbose_name_plural': 'Lotes de Siembra',
            },
        ),
        migrations.RemoveField(
            model_name='germinacion',
            name='proovedor',
        ),
        migrations.RemoveField(
            model_name='germinacion',
            name='semilla_utilizada',
        ),
        migrations.AlterField(
            model_name='rubro',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='Germinacion',
        ),
        migrations.AddField(
            model_name='cultivo',
            name='invernadero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siembras.Invernadero'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siembras.LoteSiembra'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='parcela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siembras.Parcela'),
        ),
    ]
