# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-30 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siembras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invernadero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=255)),
            ],
        ),
    ]
