# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-30 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siembras', '0002_invernadero'),
    ]

    operations = [
        migrations.AddField(
            model_name='invernadero',
            name='nombre',
            field=models.CharField(default='Invernadero', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invernadero',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
