# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-05 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siembras', '0002_auto_20160802_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivo',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode'),
        ),
    ]
