# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-30 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siembras', '0003_auto_20160730_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('fecha_siembra', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='invernadero',
            name='codigo',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='invernadero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siembras.Invernadero'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siembras.Germinacion'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='parcela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siembras.Parcela'),
        ),
    ]
