# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-27 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siembras', '0003_cultivo_qrcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lotesiembra',
            old_name='cantidad',
            new_name='cantidad_semillas_enviadas',
        ),
        migrations.AddField(
            model_name='lotesiembra',
            name='cantidad_semillas_recibidas',
            field=models.FloatField(default=0.0),
        ),
    ]
