# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-01 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siembras', '0004_auto_20160730_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteSiembra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=0.0)),
                ('fecha_enviado', models.DateField()),
                ('fecha_recibido', models.DateField(blank=True, null=True)),
                ('germinado', models.BooleanField(default=True)),
                ('proovedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siembras.Proovedor')),
                ('semilla_utilizada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siembras.Semilla')),
            ],
            options={
                'verbose_name_plural': 'Lotes de Germinacion',
            },
        ),
        migrations.RemoveField(
            model_name='germinacion',
            name='proovedor',
        ),
        migrations.RemoveField(
            model_name='germinacion',
            name='semilla_utilizada',
        ),
        migrations.AddField(
            model_name='cultivo',
            name='densidad_siembra',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cultivo',
            name='posicion_final',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cultivo',
            name='posicion_inicial',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siembras.LoteSiembra'),
        ),
        migrations.DeleteModel(
            name='Germinacion',
        ),
    ]
