# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-15 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siembras', '0005_rubroimagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivo',
            name='invernadero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cultivos_invernadero', to='siembras.Invernadero'),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='parcela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cultivos_parcela', to='siembras.Parcela'),
        ),
        migrations.AlterField(
            model_name='rubroimagen',
            name='rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubro_media', to='siembras.Rubro'),
        ),
    ]
