# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-01 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siembras', '0005_auto_20160801_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lotesiembra',
            options={'verbose_name_plural': 'Lotes de Siembra'},
        ),
        migrations.AlterField(
            model_name='lotesiembra',
            name='fecha_enviado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
