# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-01 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siembras', '0006_auto_20160801_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivo',
            name='densidad_siembra',
            field=models.FloatField(),
        ),
    ]
