# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-08 16:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('siembras', '0006_auto_20160915_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='proovedor',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 1, 8, 16, 50, 10, 729402, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proovedor',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 1, 8, 16, 50, 15, 713365, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
