# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-08 16:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('siembras', '0007_auto_20170108_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='semilla',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 1, 8, 16, 51, 31, 977021, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semilla',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 1, 8, 16, 51, 37, 297283, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
