# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-10 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siembras', '0008_auto_20170108_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='ancho_medida',
            field=models.FloatField(default=2.0),
        ),
        migrations.AddField(
            model_name='parcela',
            name='largo_medida',
            field=models.FloatField(default=1.0),
        )
    ]
