# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-10 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siembras', '0010_auto_20170110_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proovedor',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proovedor_categoria', to='siembras.Categoria'),
        ),
    ]
