# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-10 15:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('siembras', '0011_auto_20170110_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 1, 10, 15, 20, 27, 676253, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcela',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 1, 10, 15, 20, 31, 78098, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
