# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-13 20:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('siembras', '0013_auto_20170110_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 1, 13, 20, 53, 28, 646569, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cultivo',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 1, 13, 20, 53, 37, 306121, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lotesiembra',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 1, 13, 20, 53, 41, 397939, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lotesiembra',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 1, 13, 20, 53, 44, 949687, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
