# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-30 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siembras', '0015_lotesiembra_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemillaLote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_semillas_enviadas', models.FloatField(default=0.0)),
                ('cantidad_semillas_recibidas', models.FloatField(default=0.0)),
                ('fecha_enviado', models.DateField(blank=True, null=True)),
                ('fecha_recibido', models.DateField(blank=True, null=True)),
                ('germinado', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('proovedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siembras.Proovedor')),
            ],
        ),
        migrations.RemoveField(
            model_name='lotesiembra',
            name='cantidad_semillas_enviadas',
        ),
        migrations.RemoveField(
            model_name='lotesiembra',
            name='cantidad_semillas_recibidas',
        ),
        migrations.RemoveField(
            model_name='lotesiembra',
            name='fecha_enviado',
        ),
        migrations.RemoveField(
            model_name='lotesiembra',
            name='fecha_recibido',
        ),
        migrations.RemoveField(
            model_name='lotesiembra',
            name='germinado',
        ),
        migrations.RemoveField(
            model_name='lotesiembra',
            name='proovedor',
        ),
        migrations.RemoveField(
            model_name='lotesiembra',
            name='semilla_utilizada',
        ),
        migrations.AddField(
            model_name='lotesiembra',
            name='rubro',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='siembras.Rubro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semillalote',
            name='semilla_lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lote_siembra', to='siembras.LoteSiembra'),
        ),
        migrations.AddField(
            model_name='semillalote',
            name='semilla_utilizada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siembras.Semilla'),
        ),
    ]
