# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-31 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siembras', '0017_auto_20170130_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semillalote',
            options={'verbose_name_plural': 'Semillas por Lote'},
        ),
        migrations.AlterField(
            model_name='semillalote',
            name='semilla_lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semilla_lote', to='siembras.LoteSiembra'),
        ),
    ]
