# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-02 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='nro_factura',
            field=models.IntegerField(help_text='Numero de Factura'),
        ),
    ]
