# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-02 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_auto_20160802_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateField(blank=True, help_text='Format YYYY-mm-dd'),
        ),
    ]
