# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-01 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siembras', '0005_auto_20160801_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadesCultivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_realizacion', models.DateTimeField()),
                ('actividad', models.IntegerField(choices=[(1, 'Desmalezamiento'), (2, 'Riego'), (3, 'Fertilizacion'), (4, 'Plaguicida'), (5, 'Limpieza')], default=1)),
                ('observacion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrecimientoCultivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medida', models.FloatField(default=0.0)),
                ('unidad', models.IntegerField(choices=[(1, 'cm'), (2, 'mm')], default=1)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('observaciones', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CultivoMuestra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siembras.Cultivo')),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(blank=True, max_length=255)),
                ('proovedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siembras.Proovedor')),
            ],
        ),
        migrations.CreateModel(
            name='Plaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('imagen', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlagasCultivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aparacion', models.DateField()),
                ('imagen', models.CharField(max_length=255)),
                ('plaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.Plaga')),
            ],
        ),
        migrations.CreateModel(
            name='SeguimientoCultivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siembras.Cultivo')),
            ],
        ),
        migrations.AddField(
            model_name='crecimientocultivo',
            name='muestra_cultivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.CultivoMuestra'),
        ),
    ]
