# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-01 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siembras', '0006_auto_20160801_1901'),
        ('seguimiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizanteCultivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aplicacion', models.DateField()),
                ('observaciones', models.TextField()),
                ('fertilizante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.Fertilizante')),
            ],
        ),
        migrations.AddField(
            model_name='actividadescultivo',
            name='cultivo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='siembras.Cultivo'),
            preserve_default=False,
        ),
    ]
