# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-08 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crecimientocultivo',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode'),
        ),
    ]
