# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-01 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siembras', '0007_auto_20160801_1934'),
        ('seguimiento', '0002_auto_20160801_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizantecultivo',
            name='cultivo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='siembras.Cultivo'),
            preserve_default=False,
        ),
    ]
