# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-09 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0003_auto_20160808_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadescultivo',
            name='cultivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='siembras.Cultivo'),
        ),
        migrations.AlterField(
            model_name='crecimientocultivo',
            name='muestra_cultivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crecimiento_muestra', to='seguimiento.CultivoMuestra'),
        ),
        migrations.AlterField(
            model_name='seguimientocultivo',
            name='cultivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='siembras.Cultivo'),
        ),
    ]
