# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-01 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0003_fertilizantecultivo_cultivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crecimientocultivo',
            name='fecha_registro',
            field=models.DateField(auto_now=True),
        ),
    ]
