# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-01 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0004_auto_20160801_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crecimientocultivo',
            name='observaciones',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='plaga',
            name='descripcion',
            field=models.TextField(max_length=255),
        ),
    ]
