# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-11 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siembras', '0003_cultivo_qrcode'),
        ('seguimiento', '0004_auto_20160809_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(blank=True, max_length=255)),
                ('cantidad', models.FloatField(default=0.0)),
                ('medida', models.IntegerField(choices=[(1, 'cm'), (2, 'mm'), (3, 'ml'), (4, 'l'), (5, 'Kg'), (6, 'mg')], default=5)),
                ('proovedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siembras.Proovedor')),
            ],
        ),
        migrations.RenameModel(
            old_name='FertilizanteCultivo',
            new_name='InsumoCultivo',
        ),
        migrations.RemoveField(
            model_name='fertilizante',
            name='proovedor',
        ),
        migrations.AlterField(
            model_name='insumocultivo',
            name='fertilizante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.Insumo'),
        ),
        migrations.DeleteModel(
            name='Fertilizante',
        ),
    ]
