# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-11 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0005_auto_20160811_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insumocultivo',
            old_name='fertilizante',
            new_name='insumo',
        ),
    ]
