# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-11 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0006_auto_20160811_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumocultivo',
            name='cantidad',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='insumocultivo',
            name='medida',
            field=models.IntegerField(choices=[(1, 'cm'), (2, 'mm'), (3, 'ml'), (4, 'l'), (5, 'Kg'), (6, 'mg')], default=5),
        ),
    ]
