# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-27 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siembras', '0003_cultivo_qrcode'),
        ('seguimiento', '0007_auto_20160811_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cosecha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cultivo', models.DateField(blank=True)),
                ('cantidad', models.FloatField(default=0.0)),
                ('medida', models.IntegerField(choices=[(1, 'cm'), (2, 'mm'), (3, 'ml'), (4, 'l'), (5, 'Kg'), (6, 'mg')], default=5)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siembras.Cultivo')),
            ],
        ),
    ]
