# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-27 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0008_cosecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cosecha',
            old_name='fecha_cultivo',
            new_name='fecha_cosecha',
        ),
    ]
