# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-07 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0010_auto_20160915_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimientocultivo',
            name='cultivo',
        ),
        migrations.AlterField(
            model_name='actividadescultivo',
            name='cosecha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seguimiento.CosechaCultivo'),
        ),
        migrations.AlterField(
            model_name='actividadescultivo',
            name='crecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seguimiento.CrecimientoCultivo'),
        ),
        migrations.AlterField(
            model_name='actividadescultivo',
            name='insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seguimiento.InsumoCultivo'),
        ),
        migrations.DeleteModel(
            name='SeguimientoCultivo',
        ),
    ]
