# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-10 19:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0011_auto_20170107_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 1, 10, 19, 3, 52, 811348, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insumo',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 1, 10, 19, 3, 57, 179529, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
