# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-11 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0012_auto_20170110_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='proovedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumo_proovedor', to='siembras.Proovedor'),
        ),
    ]
