# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-13 17:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0014_auto_20170113_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='plaga',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 1, 13, 17, 8, 47, 468573, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plaga',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 1, 13, 17, 8, 56, 868174, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
