# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-13 20:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0015_auto_20170113_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosechacultivo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 1, 13, 20, 10, 46, 681351, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cosechacultivo',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 1, 13, 20, 10, 51, 929208, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cosechacultivo',
            name='cultivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosecha_cultivo', to='siembras.Cultivo'),
        ),
    ]
