# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-26 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0016_auto_20170113_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cosechacultivo',
            options={'ordering': ['-created']},
        ),
    ]
